// <auto-generated />
namespace Vidly.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class SetMembershipTypeNamesoffirst4customers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SetMembershipTypeNamesoffirst4customers));
        
        string IMigrationMetadata.Id
        {
            get { return "201811230729259_Set MembershipType Names of first 4 customers"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
